<?php
// $Id$

function _aoc_authorization_get_legit_users() {

  $b = db_escape_string(variable_get('aoc_tools_bebot_dbname', 'bebot'));
  $rid = db_escape_string(variable_get('aoc_authorization_role', 0));

  $query="SELECT DISTINCT {profile_values}.uid AS uid
  FROM ". $b .".users
  INNER JOIN {profile_values} ON $b.users.nickname = {profile_values}.value
  JOIN {users} ON {profile_values}.uid = {users}.uid
  WHERE {profile_values}.uid NOT IN (SELECT DISTINCT {profile_values}.uid AS uid FROM $b.users
  INNER JOIN {profile_values} ON $b.users.nickname = {profile_values}.value
  JOIN {users} ON {profile_values}.uid = {users}.uid
  JOIN {users_roles} ON {users}.uid = {users_roles}.uid
  WHERE {users_roles}.rid = ". $rid .");";
  $result = db_query($query);
  $x = 0;
  if (db_num_rows($result) >= 1) {
    while ($row = db_fetch_array($result)) {
      $return[$x] = $row['uid'];
      $x++;
      }
    return $return;
  }
  else {
    return false;
  } // no users to add
} // function aoc_authorization_get_legit_users end

function _aoc_authorization_set_legit_users() {
  $users = _aoc_authorization_get_legit_users();
  if ($users == false) {
    return true;
  }

  user_multiple_role_edit($users, 'add_role', variable_get('aoc_authorization_role', 0));
  return true;
}


/*
 * Cron Hook
 * This will be called everytime cron is run, so we try keep it nice to the system :)
 */

function aoc_authorization_cron() {
  if (variable_get('aoc_authorization_cron', 0) == 1) {
    _aoc_authorization_set_legit_users();
  }
} // function aoc_authorization_cron end


/* ////////////////////// Installation, uninstall and Updates.... ////////////// */

/*
 * Install
 */

function aoc_authorization_install() {

  // TODO: setup our profile fields
/*  db_query("INSERT INTO {profile_fields} (`title`, `name`, `explanation`, `category`, `page`, `type`, `weight`, `required`, `register`, `visibility`, `autocomplete`, `options`) VALUES
  ('Mainnchar', 'profile_mainchar', 'Name deines Hauptcharakters', 'InGame', '', 'textfield', 0, 1, 1, 2, 0, ''),
  ('Rasse', 'profile_race', 'Abstammung des Charakters', 'InGame', '%value', 'selection', 0, 1, 1, 2, 0, 'Aquilonier\r\nCimmerier\r\nStygier'),
  ('Klasse', 'profile_class', 'Klasse deines Mainchars', 'InGame', '%value', 'selection', 0, 1, 1, 2, 0, 'Assassine\r\nBarbar\r\nBaerenschamane\r\nDaemonologe\r\nDunkler Templer\r\nEroberer\r\nHerold des Xotli\r\nMitrapriester\r\nNekromant\r\nWaechter\r\nVollstrecker Sets\r\nWaldlaeufer'),
  ('Beruf 1', 'profile_profession1', 'Dein erster Beruf, sofern bereits vorhanden.', 'InGame', '', 'selection', 0, 0, 1, 2, 0, 'Waffenschmied\r\nRüstungsschmied\r\nAlchemist\r\nArchitekt\r\nJuwelenschneider'),
  ('Beruf 2', 'profile_profession2', 'Dein zweiter Beruf, sofern bereits vorhanden.', 'InGame', '', 'selection', 0, 0, 1, 2, 0, 'Waffenschmied\r\nRüstungsschmied\r\nAlchemist\r\nArchitekt\r\nJuwelenschneider');");
 */
} // function aoc_authorization_install end


function aoc_authorization_uninstall() {
  variable_del('aoc_authorization_role');
  variable_del('aoc_authorization_cron');
}  // function aoc_authorization_uninstall end
